### PR TITLE
Add new assets to footer

### LINKED ISSUE #38: Update list of assets in the footer
Someone [asked](https://www.reddit.com/r/getumbrel/comments/12rd5xj/dcrdex_on_umbrel/jkrxnmt/) on Reddit how to see which assets are supported without installing the app. I'll give them https://dex.decred.org/ but the list needs an update to add ETH, USDC, DGB which were added recently.

### PR DESCRIPTION
**Pull request by jholdstock**
Closes #38 

Screenshot from 2023-05-25 11-28-37

### CODE REVIEW

**Comment by norwnd** [comment]
Perhaps **Polygon** should also be added to the list, looks like it [might land soon enough](https://github.com/decred/dcrdex/pull/2431) ? And I think **Firo** is there already.

Another suggestion, the following list calls it **pairs** (see screenshot below): `DCRDEX currently supports trading pairs for` while it essentially means blockchains/tokens, perhaps it would make more sense to call it `DCRDEX currently supports the following blockchains`, and maybe optionally emphasise below `With most popular traded assets` (listing tokens like USDC, ~USDT~, BTC, ETH, DCR - which most people will search for) or something along these lines.

image

**Comment by xaur** [comment]
@norwnd until [Releases](https://github.com/decred/dcrdex/releases) get any mention of Polygon, Firo etc. I think it is too early to mention them. If we do want to mention them, they should go into a separate "Work in progress" section or something.

re your second point, I think "supports trading pairs for" is pretty accurate and short. If we add `blockchains` then we also have to add `With most popular traded assets` to reflect that tokens are also supported. I don't see any benefit in a making it longer and more complex.

The main use case of this list is to quickly answer "Can I trade DCR and USDC?" without bothering which of them is coin and which is token. The only thing we might add there is a tiny "ETH" superscript after "USDC" to indicate which base network it is hosted at. If anyone ever gets confused by this or asks about it

**Comment by dev-warrior777** [comment]
> @norwnd until [Releases](https://github.com/decred/dcrdex/releases) get any mention of Polygon, Firo etc. I think it is too early to mention them. If we do want to mention them, they should go into a separate "Work in progress" section or something.

Firo & Dash have been finished and ready many many months already .. 100s hours work

**Comment by xaur** [comment]
If Firo, Dash and others can be used from [release binaries](https://github.com/decred/dcrdex/releases) (currently v0.6.3 is the latest) they need to be in the list.

If they are ready and stable on `master` but not released in binaries, it is a very different form of availability where one needs to install toolchains and build from source. It's not what most users expect. If we do expose them, I'd place them in a separate list "If you build from source you also get coins X, Y, Z".

If this PR is not inaccurate I'd merge it as is since it's 6 months old now and dex.decred.org is falling behind the current releases.

**Review by buck54321 — APPROVED** [review]
This matches the current release, so this seems right. We'll do better about synchronizing these assets in future reelases. Thanks, @jholdstock.

**Pull request merged**
